### ISSUE TITLE
Added external FK support to datapackage

### ISSUE THREAD

**Issue by roll** [frictionlessdata/pilot-catalyst#2]
# Overview

The work is started here - https://github.com/frictionlessdata/datapackage-py/tree/fk-external

# Tasks

- [ ] draft the implementation
- [ ] decide on the way of referencing external data packages (relative path?)
- [ ] improve error messages on failing foreign key checks
- [ ] implement support for external FKs

**Comment by roll** [comment]
Merged into https://github.com/frictionlessdata/pilot-catalyst/issues/3
